version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fl_ingest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  stagehand:
    build: ./stagehand_service
    container_name: stagehand-service
    env_file: .env
    environment:
      - BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BROWSERBASE_PROJECT_ID=${BROWSERBASE_PROJECT_ID}
      - STAGEHAND_MODEL=${STAGEHAND_MODEL}
      - PORT=3000
    ports:
      - "3001:3000"
    networks:
      - backend

  web:
    build: .
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - .:/app
#      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      PYTHONUNBUFFERED: "1"
      PYCHARM_DEBUG: "1"
      PYTHONPATH: /app     # не обязательно, но полезно явно
      STAGEHAND_SERVICE_URL: ${STAGEHAND_SERVICE_URL:-http://stagehand:3000}
    depends_on:
      - db
      - stagehand
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
